### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by itsharshitb** [Harshitbhatt69/blog-handler#1]

**Comment by aroundarmor** [comment]
What's the issue?

**Comment by itsharshitb** [comment]
Need a readme, project is still under development.

**Comment by aroundarmor** [comment]
fine, can you provide me a little more detail about your project so that I can make a relevantly close Readme for you?

**Comment by itsharshitb** [comment]
App is under development in react native with expo, which help you to manage your blog posts. You have the options for add, delete, read and edit post. The post will be stored in json server with the help of ngrok.

**Comment by aroundarmor** [comment]
can you provide me some screenshots, so that I can mention them on your README?

**Comment by itsharshitb** [comment]
ok wait a second i am adding new directory for screenshorts

**Comment by itsharshitb** [comment]
Check it now..

**Comment by aroundarmor** [comment]
Found it and I'm working on it. Meanwhile, Can you assign this issue to me so that while I complete I'm assured that my contribution is counted?

**Comment by aroundarmor** [comment]
Done, you can now see the README of your project.

**Comment by aroundarmor** [comment]
How much do you like my work? If your issue is resolved mark it closed.

**Comment by itsharshitb** [comment]
Can you set screenshot in horizontal row and keep the size medium.

**Comment by tewarig** [comment]
you can  close this issue now
